services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    TorqIT\DataImporterExtensionsBundle\Controller\:
        resource: "../../Controller"
        public: true
        tags: ["controller.service_arguments"]

    TorqIT\DataImporterExtensionsBundle\Service\:
        resource: "../../Service"
        public: true

    TorqIT\DataImporterExtensionsBundle\Resolver\:
        resource: "../../Resolver"
        public: true

    TorqIT\DataImporterExtensionsBundle\DataSource\:
        resource: "../../DataSource"
        public: true

    TorqIT\DataImporterExtensionsBundle\Mapping\:
        resource: "../../Mapping"
        public: true

    ################
    ### EXTERNAL ###
    ################

    Pimcore\Bundle\DataImporterBundle\Mapping\Operator\Factory\QuantityValueArray:
        class: TorqIT\DataImporterExtensionsBundle\Mapping\Operator\Factory\QuantityValueArray
        tags:
            - { name: "pimcore.datahub.data_importer.operator", type: "quantityValueArray" }

    Pimcore\Bundle\DataImporterBundle\Mapping\Type\TransformationDataTypeService:
        class: TorqIT\DataImporterExtensionsBundle\Mapping\Type\TransformationDataTypeService

    Pimcore\Bundle\DataImporterBundle\Mapping\Operator\Simple\LoadDataObject:
        class: TorqIT\DataImporterExtensionsBundle\Mapping\Operator\Simple\LoadOrCreateDataObject
        tags:
            - { name: "pimcore.datahub.data_importer.operator", type: "loadDataObject" }
