name: "Frontend Build"

on:
  push:
    paths:
      - "studio/**"
  pull_request:
    paths:
      - "studio/**"
  workflow_dispatch:

concurrency:
  group: frontend-build-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  frontend-build:
    permissions:
      contents: write
    uses: pimcore/workflows-collection-public/.github/workflows/reusable-studio-frontend-build.yaml@becd699647df9e3123c5489327772396a8016dc1 # main
    with:
      working-directory: ./studio
      node-version: "26"
      build-output-path: ./src/Resources/public/build/production/